# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Candidate Name')),
                ('sign', models.CharField(max_length=128, unique=True, verbose_name='Candidate Sign')),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Polling Station Name')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Polling Station Address')),
                ('total_votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Polling Station',
                'verbose_name_plural': 'Polling Stations',
            },
        ),
        migrations.CreateModel(
            name='PollingStationVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PollingStation')),
            ],
            options={
                'verbose_name': 'Polling Station',
                'verbose_name_plural': 'Polling Stations',
            },
        ),
    ]
