# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingstationvotes',
            options={'verbose_name': 'Polling Station Votes', 'verbose_name_plural': 'Polling Station Votes'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='image_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Candidate Imag Name'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
